### ISSUE TITLE
(Pre-Visit Wizard) Storage and representation of all Project Data needed for NEB Energy Assessment Addendum

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#100]
This epic presents the initial draft of creating and managing a project in NEB Tool. The user can add a new project using the "New Project Wizard", and all of the metadata fields and connections with Strategic Goals and Production Processes are implemented.

Some key criteria:

- Users can create a new project, including the facility, company, assessment, and project data objects.
- The projects are organized into a hierarchy with the following levels: Company -> Facility -> Assessment -> Project
- Data collected in higher levels are auto-filled into lower levels when new [child] item is created.
- Metadata will be collected at each level, congruent with the NEB Assessment Protocol.
- KPI / Strategic Goal objects added to model
- Production Processes added to model.
- Contacts added to model

This epic corresponds roughly to 6.3.2 in the requirements doc.

**Comment by rmroot** [comment]
Closing epic. Pulled some issue out of epic and put in other epics.
