### ISSUE TITLE
Pre-visit and On-site data

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#104]
This epic includes any issue related to the Pre-Visit and On-site wizard data excluding NEB association UI - which is handled in another epic.

Requirements of this epic include:
- Prompting the user to investigate production processes and enter information about them (such as contacts, production process outcomes, and any pain points discovered).
- Refining the energy pre-assessment and turning it into a full assessment.
- Asking the user to review assumptions made in the pre-visit wizard around KPIs.

**Comment by rmroot** [comment]
Updating this epic to bin everything related to existing project data features

**Comment by rmroot** [comment]
moved remaining issues to new epic for protocol incorporation. Closing epic
