### ISSUE TITLE
Report View - First Draft

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#108]
This epic is meant to get a first draft of the entire wizard workflow, from beginning to end. User should be able to generate a report (at least one level of roll-up).

- Report is on its own page, located in the "third" wizard section.
- Scope of report may be a single assessment, or multiple / all assessments (project-wide).
- No customization of report is necessary for this epic, but the UI could be stubbed out for that.
- Report must roll-up energy use, quantitative NEBs (using sum) and qualitiative NEBs (using union).
- Report UI can be a list of text, graphic are a plus but not needed for this epic.

<img width="1010" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e3cd7605f8dee8c78676d6bf36b85fe24c30f97/Screenshot%202024-06-07%20at%203.16.08%20PM.png" alt="Screenshot 2024-06-07 at 3.16.08 PM.png" />

**Comment by rmroot** [comment]
### Needs for Report NREL/NEB-Tool#108
Below I have provided a quick brain dump of what I could think of would be needed for a report, most bullets could be created into issues.

- Routing and component scaffolding (issue already created #94)
- Single assessment report
    - Create data model for single assessment report results
    - Add calculation logic. Implement math for data model results
    - Define and add simple graph (data model needed). Probably will be the financial impact of NEBs broken down by associated KPI
    - Define and add tables, will be similar to graphs.
- Rollup report of multiple assessments
    - Data model will be and array of assessment results and totals. Potentially totals broken up by KPIs/NEBs
    - Add calculation logic. Math should just be summation of assessment report
    - Graphs for rollup (same as above)
    - Tables for rollup (same as above)
- Figure out how to add contacts to the report
- Figure out how to add equipment to the report
- Stretch goal will want to “Generate PDF” 
    - Not required but something somewhat easy that has significant value for demo purposes
    - Something that can be added after July 8th deadline if there is proper bandwidth
- Plotly.js dependency added to project
