### ISSUE TITLE
Clean Up Non-Wizard Content

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#109]
Use this issue to bin all non-wizard content that needs UI updates.

**Comment by rmroot** [comment]
I don't think we want to dedicate time to updating the dashboards much for demo's yet but a pass through to show their usability would be good prior to advisory board demo. Showing that reports/equipment etc exist in a facility would be a good taste of what is to come.

**Comment by rmroot** [comment]
Updating epic to match with alpha distribution timeline
