### ISSUE TITLE
Data validation requirement collection/clarification

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#113]
Objective: requirement collection and clarifications for the input form validation.

**Comment by RLiNREL** [comment]
Objective: requirement collection and clarifications for the input forms.

**Comment by RLiNREL** [comment]
Attaching a table for clarification about input field validations. This will be shared through email and individual meetings to ensure agreements across the team.
[NEB-tool_Input_Form_Validation_Clarification_Table_06-07.xlsx](https://nrel.sharepoint.com/:x:/r/sites/TripleFOAMBenefits/Shared%20Documents/General/Software%20Team/NEB-tool_Input_Form_Validation_Clarification_Table.xlsx?d=we59ac3c3c1924c859f11c075ee432dab&csf=1&web=1&e=le0QfA)

**Comment by RLiNREL** [comment]
### Kristina's comment:

For the input field:
- Number Type: no limit to decimal places
- String Type: string length should be > 200 for notes.

For the required option (two -tier):
- Must have: red error and disable to next step
- Should have: yellow warning and use default value if there is no input (such as cost and saving in assessment)

For display results:
- Limit to 2-3 decimal places

**Comment by RLiNREL** [comment]
### Jordan's comment:
> -	The underlying code base should support Latin1, Double-Byte and any other character sets that will make it possible to be translated in other languages than English. 
- Support UTF-8 (Latin1, Double-Byte, other languages)

> The NEB tool shall have fields for each KPI in which qualitative and/or historical information, e.g., past energy audits and results, can be entered. Each field should have enough character space to accommodate up to 500 words.
- No limit for qualitative and/or historical information. "Google says that text contains on average 5 characters per word, so we’re talking 2500 characters minimum. Let’s be safe and go with ~10,000 characters. I would advocate to not impose any arbitrary limit other than those necessary for UI or performance reasons."

**Comment by RLiNREL** [comment]
### Sarah's comment:
To add validation for ROI calculations and other inputs to quantify NEBs later

**Comment by RLiNREL** [comment]
### Changes 06-10-24
1. Removed max length for notes input field
2. Updated string input fields length, 1-100 for short text (company name, team member name, etc.) and 1-255 for longer text (street name, email, etc.)
2. Removed decimal places limit for number input type
3. Updated phone number pattern for US and international
4. Added a suggested column for inputs that are not required/unavailable at the beginning (default=0) but should be updated for accurate evaluation/reporting, such as costs and savings

**Comment by RLiNREL** [comment]
The validation requirements are sufficient for now. Detailed updates are included in the specific issues, such as #143 
Will revisit in the future.

**Comment by ghost** [comment]
Not sure how to review this issue, as it is unrelated to a pull request. The requirements listed here sound reasonable, although I am not sure this is the best place to keep track of them. Should I close this issue?

**Comment by RLiNREL** [comment]
This issue is closed, and the contents are moved to the [#65 Epic page](https://app.zenhub.com/workspaces/justifi---neb---ornl---nrel-61080603e73e7b0011bbdd7d/issues/gh/nrel/neb-tool/65).
