### ISSUE TITLE
Data validation company.general-details

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#114]
- [x] a router guard, which prevents the user from navigating out of the page unless ALL the required fields are filled. The company name is recommended as the only required field.
- [x] validation on zip code
- [x] non-negative numerical values

**Comment by ghost** [comment]
Reviewing v0.0.1-alpha-66703bc Company Name field is empty when a new company is created. Navigating away from the page is not possible until a company name is added.

Potential problems:
- No other information appears to be validated (zip code, state, numeric values, etc). Have the validation requirements on the Company page been loosened?
- There is no way for me to test the sidebar badge from Company details page at this time, snce the name is the only field that appears to be validated. How can I test the sidebar badges from this page?

**Comment by RLiNREL** [comment]
1. We implemented a router guard, which prevents the user from navigating out of the page unless ALL the required fields are filled. The company name is recommended as the only required field.
2. The other validations include validation on zip code (limited to [a few countries](https://www.npmjs.com/package/val-zip), like USA, Germany, Austria, Switzerland, etc.). You can test, for example, by choosing USA and putting in 12345. A warning message will show up. There is also validation on the numerical values, which cannot be negative (more specific value range can be added).
3. The sidebar UI response to invalid inputs is unnecessary any more due to the router guard and a pop up message as a reminder for user to fill the required fields before navigating out of the page.

**Comment by RLiNREL** [comment]
- For the warning (non-required invalid inputs), if navigate out of the page and come back, the warning doesn't persist.
- Show warning for empty input values or default to 0.

**Comment by ghost** [comment]
Looks good to me. I found one bug, which I added as a new issue #172
