### ISSUE TITLE
Data validation facility inputs

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#117]

**Comment by RLiNREL** [comment]
Current validation is the required field of the facility name to go to the next button.
More validations will be added in the future.

**Comment by ghost** [comment]
The facility name still has a default value of "New Facility". This is incongruent with the Company page which does not have a default value. Please remove the default value for the facility name.

**Comment by RLiNREL** [comment]
The default value of New Facility is removed.

**Comment by ghost** [comment]
As of v0.0.1-alpha-3483233, I observe:

- Facility name is blank by default, and it acts as a required field.
- Zip code is validated at warning level when United States is selected in country drop-down.
- Price is validated at warning level for non-negative and empty.

Potential remaining issues:
- Price validation reports the "empty" warning message if the user types non-numeric text. (Added bug report #172)
