### ISSUE TITLE
Deselected KPIs, Processes, and Nebs should not be hidden in later pages.

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#121]
There are a few places in the UI where we have the user "select" or enable data objects, and then fill in their details on the next page. Currently, the deselected objects are hidden on the details page, but we should explore ways to keep them visible but just a bit more hidden. For example, de-selected KPIs could be visible on the details page, but the might be lower on the page or grayed out. Could also consider merging the "selection" and "details" pages into one UI.

The overall goal of this issue is to avoid confusing the user if they do to the "details" page looking for something they've not already selected.

**Comment by rmroot** [comment]
UI has been updated so that the DB can be searched whenever a DB entrance is not selected. This stale. Closing
