### ISSUE TITLE
Review embedded data for accuracy before demo

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#122]
This issue covers reviewing the embedded data (e.g., KPIs, KPMs, NEBs) and other data from the assessment protocol for accuracy.

- [ ] Review NEBs list in software tool, and ensure it matches those in the spreadsheet.
- [ ] Review the KPIs/KPMs and their content (units, baseline, etc) to ensure they match those in the spreadsheet.
- [ ] Review the connections between KPMs and NEBs.
- [ ] Review the energy equipment.
- [ ] Review the production processes.
- [ ] Final check for accuracy in other pieces of the tool.

**Comment by rmroot** [comment]
Stale Issue. Closing
