### ISSUE TITLE
Report page implemented in HTML

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#124]

**Comment by rmroot** [comment]
An initial assessment report has been created. Currently data has just been added as tables to demonstrate some math is being done with regards to NEBs and KPIs. Further issues are to come for a more detailed report. Anew issue for a rollup report (combining multiple assessment reports from a visit) has been added #148

**Comment by ghost** [comment]
This is implemented as of v0.0.1-alpha-c933213 in the Data Evaluation tab of the wizard. There is a new page created for each assessment, and each page shows an HTML view of a report. There remains work to be done to meet the description of epic #108, but the scope of this issue was more limited.
