### ISSUE TITLE
Modify Baseline KPM Data in NEB form

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#141]
I have the baseline input data for KPMs that are used to quantify NEBs disabled in the NEBs form. This data should be editable. The current reason it is disabled is because those values are used in multiple areas for different NEBs and we don't want to edit something that isn't being displayed. We will need to add the proper user messaging for functionality but it is important functionality. Currently you have to go back to the KPM data section, this is also lacking the right user messaging when changes are made here as well.

**Comment by koay9f** [comment]
Ability to lock down after done to let user know it is saved
Just in the same dropdown where you unlocked it

**Comment by RLiNREL** [comment]
related UI/UX issues around edit/lock baseline values with #223

1. The user has to click on the KPM again to see the Lock Baseline Option -> perhaps convert the dropdown list to buttons, view KPI details, edit baseline values (lock baseline value could be shown conditionally, i.e., edit baseline value button is clicked), so the users can see all the options available (grey out/disable button as needed). -> Alternatively, implement just one button "Lock Baseline Value" for all KPMs, regardless if it is associated with multiple NEBs or not. User can click to unlock to edit values or lock to prevent from editing (make the baseline values as locked by default and show the warning messages when associated with multiple NEBs).
2. If user clicks Edit baseline and makes some changes, then click to other page, then navigate back Lock Baseline option is gone and changed to default Edit Baseline -> consider making baseline editable as a field of KPM entity and save it to Database for persistence
3. Another consideration is, when there are multiple NEBs references to same KPM, when the baseline value in NEB A is made editable, should the baseline values in NEB B be also made editable? -> making baseline editable saved into Database could achieve this.

**Comment by koay9f** [comment]
I have no opinion on the other alternatives.  hopefully soon we'll have a thrusday call where people show up and we can ask.
