### ISSUE TITLE
Data validation sidebar UI responses to invalid form

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#143]

**Comment by RLiNREL** [comment]
When an invalid form is detected (basically, the required fields are missing in the form), the sidebar link/route should show some responses. Possible behaviors:
1. Warning icon added
2. Disabling all the links to next steps
3. Add additional messages if the disabled link is clicked

The implementation is changed to a router guard issue #142 that prevents the user from navigating to other links (e.g. home) if there is an empty required field.

**Comment by ghost** [comment]
Reviewing v0.0.1-alpha-66703bc I am unable to trigger any badges or changes to the sidebar. Since it appears this has been tabled for now, I will put this back on the product backlog for future consideration.

**Comment by RLiNREL** [comment]
The sidebar UI responses are not necessary any more due to the router guard implemented.

**Comment by ghost** [comment]
I will close this for now, in favor of a new Zenhub issue to review this mechanism: [Zenhub Issue 8](https://app.zenhub.com/workspaces/justifi---neb---ornl---nrel-61080603e73e7b0011bbdd7d/issues/zh/8)
