### ISSUE TITLE
Finish pre-visit button currently goes to "new facility" page in my portfolio.

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#144]
**Preconditions:**
In version v0.0.1-alpha-f851d6b
Finish the pre-visit wizard and click the "Finish Pre Visit" button in the lower right corner on the pre-assessment page.

**Expected behavior:**
It should either redirect to the setup wizard start page, /setup-wizard/getting-started, or just automatically open the on-site wizard.

**Observed behavior:**
The application redirects to the "facility home" route, for example: /facility/iwlbxjjxr/home.

**Other notes:**
May also want to rethink the idea of formally separating the wizards, and instead move to a single wizard with three clearly defined sections.

Removing the "My Projects" UI entirely is specified in Issue #97

**Comment by rmroot** [comment]
Issue #145 solves this problem. No longer a "Finish Pre-visit" button, it just goes directly into the "Data Collection" wizard.

**Comment by ghost** [comment]
Fixed as described as of v0.0.1-alpha-c933213.
