### ISSUE TITLE
Merge wizards into a single wizard with three sections

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#145]
Having three separate wizards was a nice way to conceptualize the flow of the tool, but in practice it may be confusing to the user. I'd like to develop an alternate UI to three separate wizards, where they are combined into a single wizard with three sections. We'd want to retain the ability for the user to easily jump into the wizard at the three existing starting points. But once inside of the wizard, they should be free to navigate back and forth throughout every section.

For example, the /setup-wizard/getting-started page currently has three buttons, one for each wizard. Instead, it could be redesigned to:
- List of all in-progress wizards / projects.
- Ability to jump to Pre-visit, On-site, or Post-visit sections for each in-progress wizard.
- Ability to create, delete, save, and load wizards.

Here's a mock-up of what this page could look like:
<img width="1383" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVNWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc035af215f036d9300ace0475fcb12972b2c40c/Screenshot%202024-06-26%20at%204.23.10%20PM.png" alt="Screenshot 2024-06-26 at 4.23.10 PM.png" />

And here's a rough mockup of what the sidebar could look like with sections:
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a95b6c93279cad470c299796e43923e105c87f8/Screenshot%202024-06-26%20at%204.24.07%20PM.png" alt="Screenshot 2024-06-26 at 4.24.07 PM.png" />

**Comment by rmroot** [comment]
I think this is spot on and have implemented in the report PR. Additionally, the "Gettting started page" was not necessary after these changes. The "Setup Wizard" button just opens the modal that page had been opening so you can just directly into the wizard

**Comment by ghost** [comment]
As of v0.0.1-alpha-c933213, the "getting started" page has been removed and now the only entry-point into the wizard environment is through the modal. The user can navigate between wizard sections using the sidebar. This could use some refinement in future pull requests.

There remains some work to be done in allowing the user to switch between active wizards, but I realize this is more-or-less a duplicate of the content of #95, so I will update that epic with the remaining items. Namely: List of all in-progress wizards / projects, and ability to create, delete, save, and load wizards.

One small issue in the current implementation which could be fixed as part of this ticket:
- [x] "Pre-Visit" is not an option in the "Select wizard step" drop down in the modal.

**Comment by rmroot** [comment]
Added pre-visit option to dropdown in modal

**Comment by ghost** [comment]
Looks good as of v0.0.1-alpha-66703bc! Thanks, Mark. Closing this issue.
