### ISSUE TITLE
"Potential NEBs for New Assessment" modal is blank if no KPIs selected

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#146]
**Environment:**
- Safari on Mac
- NEB Tool v0.0.1-alpha-f851d6b

**Preconditions:**
- Create a new wizard and skip as much as you can.
- In particular, do not add any KPIs to the pre-visit page.
- Navigate to the on-site wizard.
- Add a new assessment by clicking the "Add assessment" button.

There are two ways to trigger the bug. First way:
- Navigate to the Assessment Level nebs page.
- Click on "+ Add Assessment NEBs"

Second way:
- Navigate to the "Energy Opportunities" page
- Click "Add energy opportunity"
- Click "Find NEBs"

**Expected behavior:**
- The NEBs modal should show all available NEBs in the database, and allow me to add nebs to my project.

**Observed behavior:**
- The NEBs modal is blank (see screenshot).

<img width="993" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e16cef85100e35251cdc6387b3f45c6482037d9c/Screenshot%202024-06-26%20at%204.33.33%20PM.png" alt="Screenshot 2024-06-26 at 4.33.33 PM.png" />

**Comment by rmroot** [comment]
Kind of a duplicate of #136

**Comment by ghost** [comment]
Fixed as of v0.0.1-alpha-66703bc with the "Display NEBs without tracked KPMs" toggle, which is "on" by default.
