### ISSUE TITLE
Custom NEBs

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#155]
Need to be able to create custom NEBs. Will have to figure out a way to make them quantifiable and tie to KPI/KPMs

**Comment by ghost** [comment]
As discussed in the standup, we need to change the name of "+ Add Neb" button to "Add Custom Neb" and change the name of "Search Nebs" to "Add NEB."

May want to revisit the decision to have two buttons on the assessment and energy opportunity page, instead adding a "create custom neb" button to the "search nebs" modal.

**Comment by RLiNREL** [comment]
A new issue is created with the name changes for search/add NEBs #179

**Comment by RLiNREL** [comment]
Another comment from Bruce in DOE demo was to think about the broader NEBs, like incentive and rebate from utility companies. How could we incorporate more general NEBs? Will get some feedback from the research team on this.

**Comment by rmroot** [comment]
Given the new issues, this issue can be closed
