### ISSUE TITLE
Split contact name as first and last names in DB

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#158]
Currently, there is a full name property for contacts, although there are two form inputs: first name and last names. The data validation combines the first and last names before saving to DB, and splits the full name with a comma splitter to first and last names.
For consistency and to avoid name splitting and combining processes, it is better to refactor the DB schema to have first name and last name attributes. It also be helpful to sort the contact cards by last name later.
The change may affect a range of things, including import/export backup files, components handling the UIs. But the benefit is better structured data models and streamlined processes.

**Comment by rmroot** [comment]
Splitting the name into first and last in the object would be great. A pipe can then be used for the contact for display purposes.
