### ISSUE TITLE
Energy Equipment Fields

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#163]
Update energy equipment fields to match with kristina's feedback from her review: These details are a WIP

<img width="659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmpwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47692f21a9f241944026bc38460f0d7880df705d/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
Kristina suggested a page as reference: https://measur.ornl.gov/calculators/electricity-reduction
Note the quick results at the bottom of the page.

**Comment by koay9f** [comment]
said this in #204, but need "Number of Equipment" added.  integer

**Comment by rmroot** [comment]
This issue needs further update from @koay9f

**Comment by RLiNREL** [comment]
summary of the relationship of equipment type, utility type, unit options in a table
| Equipment Type  | Utility Type                                         | Size Unit Options                    | Default Unit |
|-----------------|------------------------------------------------------|--------------------------------------|--------------|
| Pump            | Electricity                                          | Power Units:  kW, W, HP, kJ/hr, etc. | kW           |
| Fan             | Electricity                                          | Power Units                          | kW           |
| Process Heating | 'Natural Gas', 'Other Fuels', 'Electricity', 'Steam' | Power Units Other Fuel (rate x HHV)  | kW           |
| Compressed Air  | Electricity                                          | Power Units                          | kW           |
| Steam           | 'Natural Gas', 'Other Fuels', 'Electricity'          |  Power Units Other Fuel (rate x HHV) | kW           |
| Process Cooling | Electricity                                          | ton, kW                              | kW           |
| Motor           | Electricity                                          | Power Units                          | kW           |
| Lighting        | Electricity                                          | Power Units                          | W            |
| HVAC            | Electricity                                          | Power Units                          | kW           |
| Mobile          | 'Electricity', 'Natural Gas', 'Other Fuels'          |  Power Units Other Fuel (rate x HHV) | kW           |

**Comment by koay9f** [comment]
I would say this total needs two results
1 - energy units as set by company
2 - energy units as set by utility (per table above, and options chosen in facility; it is NG and you have NG in MMBTU, if it was an electricity, then it is with electricity's units)
![image](https://github.com/user-attachments/assets/a7eea27f-24c0-498c-b3ed-2a0fe0c5feae)

**Comment by RLiNREL** [comment]
is this good? May need some clarifications @koay9f 
![image](https://github.com/user-attachments/assets/db75ef97-10e9-423b-865d-28a16bd76ba5)

**Comment by RLiNREL** [comment]
Feedback on changes to make:
1. add another number for annual energy use in a unit for that particular utility type set in the facility settings.
<img width="1281" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU0xQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06cee7b67427d0de0bb7e60b6aa54e3f9110c7a4/image.png" alt="image.png" />

**Comment by koay9f** [comment]
looks good.  hopefully small fix:
if utility type unit (set in facilities) == company utility unit, then don't show the # in parentheses:
 <img width="1812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTFRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73d418486fce0ee916936254d1d11fcddd4e4703/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
11/7 testing scenario feedback: change the default values for loadfactor and efficiency to 100%
