### ISSUE TITLE
Remove utilities from company, but keep under facilities

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#175]
This was briefly mentioned by @rmroot during DOE demo. The general intention is to maintain and track utilities at the facility level.

**Comment by rmroot** [comment]
connected to #162 Re-organize order of pre-visit

**Comment by rmroot** [comment]
There's a bigger issue with moving re-organizing pre-visit but let's just have this one focus on removing the utility settings from company
