### ISSUE TITLE
KPM customization to allow unit change

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#176]
This was requested by Bruce during DOE demo meeting. Allow some customizations around KPI details, for example, hr/yr to week/yr.

**Comment by rmroot** [comment]
Will have to evaluate the importance of /yr /hr etc. We will want to customize the units that are in a KPM

new issue #231

**Comment by rmroot** [comment]
In the changes made for #205 I added the ability to set the units in a kpm and created a new issue for the time period #231
