### ISSUE TITLE
Neb UI Quick Fixes

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#179]
To be more clear, suggestions from DOE demo meeting:

- [x] Change "Add NEBs" to "Search NEBs"
- [x] Change "Create Custom NEBs" to "Add NEBs"
- [x] Make NEBs box more distinctive
- [x] Make KPMs boxes more distinctive

**Comment by rmroot** [comment]
Maybe put the "Create Custom Neb" inside of the modal.

**Comment by koay9f** [comment]
Don't really need this screenshot, but overview from Nate/Bruce call 2024/08/15
<img width="1240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5e992b11e2b63e9a1845bfa0618e4c05bd26218/image.png" alt="image.png" />
