### ISSUE TITLE
Advisory Board Demo

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#184]
Bin capturing all issues that should be completed for advisory board demo.

Demo Date: October 24 (tentatively)

**Comment by RLiNREL** [comment]
The next board meeting should be October 24. It is one month before the completion of phase 1. We can push some low-priority functionalities back to after the demo if needed.

**Comment by koay9f** [comment]
Creating company, facility, equipment, KPMs, assessment + creating NEBS/KPMs is what we are wanting to show to the board
Workflow is critical b/c workflow
Every factory is UNIQUE, so customs is critical.  Showing different calcs, different situations.

**Comment by rmroot** [comment]
Closing epic. Moved issues to proper places that were not completed. Well done team
