### ISSUE TITLE
KPM List Check

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#194]
Need to vet the KPM list. Make sure labels and associations make sense. Add/Remove any needed..

We will be making issue to work through each KPM for quantification calculations and will need this done prior

List of KPIs and associated KPMs
[KPI-KPM List.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22f5b81a9d2cc2c059b73f694646db1be32c6cef/KPI-KPM%20List.docx)

**Comment by koay9f** [comment]
remove the energy cost KPM.  this should always be part of reports, don't need to call it out as a kpm/kpi

**Comment by rmroot** [comment]
I took a pass through the KPI and KPMs to use the new calculation methods where appropriate. There are only a few left that don't have a calculation method. 

Removed energy cost KPI
