### ISSUE TITLE
Ability for user to add custom neb and kpi associations to the global database.

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#199]
Currently, the user adds and customizes NEBs at the assessment and energy opportunity level within a wizard. The sponsors have indicated a desire to add a feature to save these customized connections to a global database that is shared across all projects.

**Comment by RLiNREL** [comment]
This is part of #167 [#167](https://app.zenhub.com/workspaces/justifi---neb---ornl---nrel-61080603e73e7b0011bbdd7d/issues/gh/nrel/neb-tool/167)
It also connects to #180
