### ISSUE TITLE
Draft and upload initial Contributing and READMEs to repository.

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#2]
This work includes

- [x] Deciding on git workflow / branch structure
  - main (state of recent release), develop (code for next release), feature (new commit for features), issue branch? (off develop), hotfix (off main) 
- [ ] Add PR / merge rules to git
- [ ] Pull request template
- [x] Release and versioning standards (semantic versioning standard, start on alpha v0, beta for phase 1 test)
- [x] Add standard for how to add / suggest issues for backlog
- [ ] ???

**Comment by jordanperr** [comment]
Closed in PR #9
Adding Pull request template to backlog.
