### ISSUE TITLE
Small things from conversation with Nate and Bruce

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#204]
- [x] * Review next tabs (some are not going to next page)
- [x] * HEADER/Page title: `Energy Equipment` --> `Industrial System Inventory`
- [x] * HEADER/Page title: `End Us`e --> `End Use Inventory` 
- [x] * Pre-Assessment/Assessment: `Energy Equipment` --> `Assessment Type`
- [x] * Pre-Assessment/Assessment: `Assessment Type` --> switch the enum to the MEASUR assessment list (not sure if should have water or not) (Will add a tag for `Energy Equipment` i.e., name of equipment in another issue)
- [x] * End Use: `Equipment Name` --> `End Use Name`
- [x] * Energy Opportunities /NEB: `Direct Cost Impact` --> `Financial Benefit`
- [x] *  Energy Opportunities /NEB: `NEB Impact` --> `KPM Impact on NEB` (I'll admit, not sure the final one, if make NEB/KPM section more distinct, then can probably just go with `Impact`
- [x] *   Energy Opportunities /NEB: `NEB Cost Impact` --> `Financial Impact`

**Comment by koay9f** [comment]
This has the locations of all the verbiage changes.  the ppt has other issues in it with it, just ignore those for this issue.

[feedback Nate-Bruce 20240815.pptx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e31f3a364f6e759b24d3f2a716d534d9132a953/feedback%20Nate-Bruce%2020240815.pptx)

**Comment by RLiNREL** [comment]
> Review next tabs (some are not going to next page)

The broken link I can find is from General Details to Energy Equipment under facility. It skips Energy Equipment and directly goes to Process Equipment. This is fixed. Please let me know if this is not what it means or if there is more to fix.

**Comment by RLiNREL** [comment]
> HEADER/Page title: Energy Equipment --> Industrial System Inventory

any changes needed for the equipment fields?
<img width="1100" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2xwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--519cf981c3f084a34442458855493ee745f226d6/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
>  HEADER/Page title: End Use --> End Use Inventory

any change to the "add equipment" button and default end use name, for example, "New End Use"?
<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3RwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b22cd364f57296ec97e2799bd67fe8667d04683/image.png" alt="image.png" />

**Comment by koay9f** [comment]
Everything else is good.  these still have old text
- [x] * Energy Opportunities /NEB: NEB Impact --> KPM Impact on NEB (I'll admit, not sure the final one, if make NEB/KPM section more distinct, then can probably just go with Impact
- [x]  * Energy Opportunities /NEB: NEB Cost Impact --> Financial Impact
In a custom NEB/KPI/KPM and "library" NEB/KPI/KPM
<img width="351" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME4vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aee93b323ac5dc1812176f2b02f208d494247c41/image.png" alt="image.png" />
