### ISSUE TITLE
Assessment Fixes

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#207]
Name changes & Enum change detailed in other issue
Equipment Connection in other issue

1 - Energy Use needs to be dynamic based on Assessment Type.  Might have multiple types of energy use.  
<img width="1336" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUJnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10b81b37a47c678067749afd2b616cbe54208970/image.png" alt="image.png" />

2- Something in Energy Opportunities & NEBS to show what industrial system the assessment is for
break into separate issue if needed
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVJnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c75196696dbcdaea700a1a6f9949cb3b10620aa3/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
After discussion with @koay9f , the workflow is,

1. The user chooses an assessment type
2. Based on the assessment type, offer a list of associated utility types to choose from. Note that **ONE** assessment type can be associated with **MULTIPLE** utility types at the same time eventually (some unit conversions issues and impact to the NEB calculations). But for now, it is ONE to ONE relationship/ one assessment type associated with one utility types. The complexity of associations with multiple utilities at the same time will be addressed in other issue.
3. Based on the utility type, offer a list of units to choose from.

**Comment by koay9f** [comment]
It looks like there is a default selection for Utility Type happening when you change the Assessment type.  
It would be good if Process Heating & Steam's default was Natural gas.
If you have water, it puts you on water (excellent) and that is all you can select.  Conversely, when you have an energy, you cannot select water as your utility type.  If you go from pump to PH or steam, it stays on electricity, but if you go from water to PH or steam it DOES select natural gas.

This morning we talked about having this be checkboxes I think.   If we are going through with that, then use the above as defaults (Steam & PH should be "Natural Gas" only; Treasure Hunt should be electricity and NG).  Also make a note in this issue and I will make note when reviewing.

Water's default unit should be kgal
Natural gas's and other fuel's default unit should be MMBTU

I forgot we had them as options, but ...
Steam should have the utility type option: "Steam" (with units: klb (default), lb, kg, tonne + energy units)
Compressed air have the utility type option: "Compressed Air" (with units: kscf (default), m^3)

point 2 is good

**Comment by koay9f** [comment]
Also - I just noticed my selection for the unit in assessment isn't saving when I navigate away from the page

**Comment by RLiNREL** [comment]
Changes to make:
- [x] Make sure the default utility type is selected for the selected assessment if assessment type is changed (ignore what was selected for previous assessment type)
- [x] Unit options with default unit for different utility type, similarly, the default unit is chosen if utility type changes
- [x] Persistence with the selections (navigate out and back in)

**Comment by RLiNREL** [comment]
Two tables to capture the logics and relationships:
| Assessment Type | Utility Type                                                                     | Default     |
|-----------------|----------------------------------------------------------------------------------|-------------|
| Pump            | Electricity                                                                      | Electricity |
| Fan             | Electricity                                                                      | Electricity |
| Process heating | Natural Gas                                                                      | Natural Gas |
| Steam           | Natural Gas                                                                      | Natural Gas |
| Compressed Air  | Electricity                                                                      | Electricity |
| Water           | Water                                                                            | Water       |
| Treasure Hunt   | Electricity, Natural Gas                                                         | Electricity |
| Other           | Electricity, Natural Gas, Other Fuels, Water, Waste Water, Steam, Compressed Air | Electricity |

| Utility Type   | Energy Unit Options              | Default |
|----------------|----------------------------------|---------|
| Electricity    | ENERGY                           | kWh     |
| Natural Gas    | ENERGY                           | MMBtu   |
| Other Fuels    | ENERGY                           | MMBtu   |
| Water          | VOLUMELIQUID                     | kGal    |
| Waste Water    | VOLUMELQUID                      | kGal    |
| Steam          | STEAM:klb, lb, kg, tonne, ENERGY | klb     |
| Compressed Air | VOLUMEGAS                        | kscf    |

**Comment by koay9f** [comment]
2 things: 
* Correction to the above logic
* Energy unit consistency

1 - Like equipment
<img width="714" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkF2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e7d725ee7115e7d25fa0ff7b6ee67ec651df1c9/image.png" alt="image.png" />

 
2 -  the energy unit through out the assessment needs to match the specified energy (or dropdown that's default matches the specified)

Also, to account for "Water" maybe have Annual Energy Use and Annual Energy Savings become Annual Utility Use and Annual Utility Savings (at least when water, if not always)

<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1ddc3910d0fde6bcb8b05c71191bae1b17c89bf/image.png" alt="image.png" />

<img width="1263" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBendxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c84e5d89544815a9e2be20f4f5900b979639f425/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
1. updated.
2. fixed.

> Also, to account for "Water" maybe have Annual Energy Use and Annual Energy Savings become Annual Utility Use and Annual Utility Savings (at least when water, if not always)

The utility settings are updated to be similar to pre-assessment page, i.e., allow multiple utility types under single assessment. Thus, the wording change for Water may not apply, for example, if both Water and Electricity are both chosen, we will just call it Annual Energy Use and Annual Energy Savings. However, if @koay9f feel the wording change is necessary when Water is the only utility chosen, we can add that logic in. Thanks

**Comment by koay9f** [comment]
since we decided to skip water for now, I think we can leave that...

Utility type:
Steam should also have the Steam Utility
Compressed air should also have the Compressed Air Utility

Savings unit matching:
looks good for Energy Efficiency Opps page, but still not right on Details page.
<img width="1207" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bba6e04d2b597fdfe3aae182988ec2274ed7ef3a/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
> since we decided to skip water for now, I think we can leave that...

Created a new issue #289  to get back on water/waste water unit systems

> Steam should also have the Steam Utility
> Compressed air should also have the Compressed Air Utility

Added, but the existing assessments are not updated (need manually add the new utility to exported json and re-import)

> Savings unit matching

Updated savings unit is changing based on the number of **included** utilities
