### ISSUE TITLE
Total Energy

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#211]
Ability to have Total Energy for systems with multiple energy types (TH & Hybrid PH)
Impacts: Industrial systems, pre-assessment, assessment, Energy opportunities 

* ability to set a unit for total energy
* fields/results for "total energy" as needed

**Comment by RLiNREL** [comment]
@koay9f could you provide some guidance on the energy conversion from mass (kg, lb), volume liquid (kgal), volume gas (kscf) to common energy unit (kwh/MMBtu/J)? Thanks!

Also, should we consider using different notations to distinguish these units from standard mass and volume measurements? e.g. kg-energy, kgal-energy?

**Comment by RLiNREL** [comment]
The total energy is implemented in the pre-assessment page [PR 251](https://github.com/NREL/NEB-Tool/pull/251)

The remaining and related issues are split into other issues:
- #237 adding energy use to facility page
- #249 unit conversion from unconventional energy units
- #247 connect facility page utility settings with pre-assessment
- #248 plug in total energy in on-site page and reports

**Comment by koay9f** [comment]
If the "collection" or price unit is in mass or volume, then you need to ask users for the "Higher Heating Value". For Natural Gas we can provide this 0.001029 MMBTU/scf and do conversions for any other gas volume or energy unit.
We can also probably have a list of common materials in a dropdown for other fuels with HHV. VERIFI has all this. but for now, a field with HHV should be enough.
