### ISSUE TITLE
My Portfolio Page

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#214]
Update my portfolio page for with portfolio content and working navigation.

**Comment by RLiNREL** [comment]
@koay9f could you show a screenshot to elaborate? Thanks

**Comment by rmroot** [comment]
No screenshot needed. Gonna make a pass through the general navigation outside of the wizard to clean things up.

**Comment by rmroot** [comment]
Updating issue so that it directly relate to my portfolio page. Epic encapsulates original issue and is now broken down into individual pages.
