### ISSUE TITLE
New Verbiage Changes

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#219]
New verbiage changes from discussion with DOE and research team [Link](https://nrel.sharepoint.com/:p:/r/sites/TripleFOAMBenefits/Shared%20Documents/General/Software%20Team/DOE%20Updates/NEBs%20Software%20Verbiage%2008.26.24.pptx?d=w118af22395cf4cd48c3927d39dff5c44&csf=1&web=1&e=e2gf8n)

- [x] Welcome to JUSTIFI message -> Use this tool to identify and estimate the potential non-energy benefits that could be generated during the energy assessment.
- [x] Explore NEBs message -> Explore potential energy efficiency opportunities with Non ...
- [x] Contact card -> Role -> title, remove focus area
- [x] Find KPIs 1. title add (KPIs) acronym, 2. Find common KPIs -> potential KPIs, KPI's -> KPIs
- [x] KPI detail: quantitative or qualitative metric -> metric type
- [x] End Uses Inventory sidebar -> End Use Inventory
- [x] Pre-assessment/assessment page: Visit Date/Scheduled for -> assessment date
- [x] Energy Opp: 1. Title Energy Opportunities -> Energy Efficiency Opportunities, 2. Add a subtitle "Energy Efficiency Opportunity", 3. +Add Energy Opportunity -> delete Energy, 4. Remove Energy from default name, "Energy Opportunity Notes", 5. Details message: Provide details about this energy efficiency opportunity.
- [x] Non-Energy Benefits description -> Use + Add NEB to add Non-Energy Benefits () that are directly associated with this opportunity.” Remove: the second sentence “Use the…database for potential NEBs.”
- [x] Reports: Non-opportunity Energy Savings/total Non-opportunity savings -> Additional Operational Benefits

Documentation team to revisit later:
- Welcome message: revisit this intro sentence to capture how identifying NEBs should bring attention to the broader impacts of energy efficiency opportunities
- KPI naming convention, for example, Reduce Expense Cost
- update KPI description text
- revisit Industrial system inventory field names, review the field names that will change based on the Industrial System selected above
- NEB card: Revisit the terminology “Performance Metric” and “Impacts” 
- NEBs tab: revisit this page when implementing a section for the NEBs that can’t be tied to a particular Energy Eff Opp,
- NEB tab: Revisit this page when additionally implementing a section for NEBs that all in the same category and are best represented as a cumulative/aggregate calculation
- Report: Savings need consistency throughout? Revisit the words around savings/cost/benefits/impact

**Comment by koay9f** [comment]
adding the "revisit later"  to a new issue
