### ISSUE TITLE
Emissions NEB

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#236]
Remove this and add these:

* KPM: GHG Emissions ; KPIs: Scope 1, Scope 2, Scope 3;  X = kg or %
* Air Pollutant Emissions; KPIs: Particulate, NOx, SOx, CO, % of tests that meet regulatory standards;   just % for now
* Water Pollutant Emissions; % of tests that meet regulatory standards;  just % for now

**Comment by rmroot** [comment]
Something needs to be done with this issue prior to alpha release

**Comment by koay9f** [comment]
Attempt 2
Removing one KPM and its KPIs
Adding KPMs, KPIs, NEBs

Remove: CO, CO2, NOx, SOx emissions KPM & it's KPI


Add:
KPI: GHG Emissions
KPMs: 
* Scope 1 Emissions
* Scope 2 Emissions
* Scope 3 Emissions
All three - Reported as Cost Per Unit, Percent Total, (and sure Direct Cost, why not)
Associated NEBS for all three:
* Reduced GHG Emissions (New NEB)
*  Reduced Regulatory Costs (New NEB)

KPI: Air Pollutant Emissions
KPMs:
* Particulate Emissions 
* NOx, SOx, CO Emissions
* % of tests that meet regulatory standards
All three - Reported as Percent Total or Direct Costs
Associated NEBs :
* Air quality improvement of ambient air, Reduced need for protective equipment (for all three)
* Reduced dust emissions (just for particulate)
*  Reduced Regulatory Costs (New NEB) (for all three)

KPI: Water Pollutant Emissions
KPMs:
* % of tests that meet regulatory standards
Reported as Percent Total or Direct Costs
Associated NEBs:
* Improved Water Quality (New NEB)
*  Reduced Regulatory Costs (New NEB)


KPI: Water Consumption
New KPM: 
* Sewage Costs
Associated NEBs:
* Reduce sewage volume
* Reduce water consumption

**Comment by rmroot** [comment]
Updated comment to swap KPI/KPM
