### ISSUE TITLE
Facility energy use

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#237]
<img width="949" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9mQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de97ba5bb750e02fe378a49b076a2f8c0aa986f2/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
@koay9f 

1. Would you like something like this? Each utility type has a energy use/yr with unit and a price $/energy unit.

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1gvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1ce0b99aeb43a9bc014ff7a899aabda916b491f/image.png" alt="image.png" />
