### ISSUE TITLE
NEB DB guidance modal

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#241]
The list of NEBs is really intimidating.  
New names will help, but here's some additional ideas

Search via KPM / KPI - If I search "Safety" then the NEBs related to the Safety KPI would show up

NEB names are links to another modal or side panel help.
This help includes and KPM (and KPIs) associated with the NEB, if those are tracked (YN) and if yes, the current baseline?

**Comment by RLiNREL** [comment]
push back this to after board demo
