### ISSUE TITLE
Tie in with facility utility settings to pre-assessments

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#247]
The tracked utility settings (unit and price for each utility) in the facility page should be linked to the total energy and energy cost calculations in pre-assessment.

- [x] The selected unit for each utility type on the facility page should be the default unit when a new pre-assessment is created.
- [x] The entered price for each utility type on the facility page should be used to calculate the annual costs (price x total energy use x unit conversion)

**Comment by koay9f** [comment]
Just changed from MMBTU to kWh. It will update properly if I change the values, but not if you just change the unit and don't update anything else.
<img width="1256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGN2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--253e6ae493784cced96006f1831297c54bd53055/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
This is likely related to the company unit change and fixed.
