### ISSUE TITLE
unit conversion from mass/volume to standard energy

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#249]
This issue is to implement the unit conversion from unconventional energy units (kg, lb, kgal, etc.) to standard energy units (kwh, mmbtu, etc.)

**Comment by RLiNREL** [comment]
Move the comment from #211 to here. Need help from @koay9f 

1. Could you provide some guidance on the energy conversion from mass (kg, lb), volume liquid (kgal), volume gas (kscf) to common energy unit (kwh/MMBtu/J)?
2. ~~Also, should we consider using different notations to distinguish these units from standard mass and volume measurements? e.g. kg-energy, kgal-energy?~~

**Comment by RLiNREL** [comment]
Move Kristina's comment from #211

> If the "collection" or price unit is in mass or volume, then you need to ask users for the "Higher Heating Value". For Natural Gas we can provide this 0.001029 MMBTU/scf and do conversions for any other gas volume or energy unit.
We can also probably have a list of common materials in a dropdown for other fuels with HHV. VERIFI has all this. but for now, a field with HHV should be enough.

**Comment by RLiNREL** [comment]
Feedback from @koay9f 
for steam: instead of HHV use "Enthalpy" for compressed air instead of HHV use "Specific Power"

**Comment by koay9f** [comment]
math and all looks good.  
weird css thing for Compressed air & steam
<img width="1871" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2674370eee71b4ee330e2844f8d50d42812c87b1/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
weird css thing for Compressed air & steam: fixed
