### ISSUE TITLE
Total Energy Cost in Opportunities

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#258]
We should be able to calculate the total energy cost within and opportunity the same way we do within an assessment given the energy use

**Comment by RLiNREL** [comment]
For the assessment, the total energy use and cost are calculated based on the energy uses in each associated utility type. If we would like to do the same for each energy opportunity, we would need a table. @koay9f could you share your thoughts?
1. a list of opportunity types
2. association of utility types to each opportunity type, such as,
<img width="717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlV5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae83b1c8ee493c776de0652031ce71574fac0fc6/image.png" alt="image.png" />

<img width="938" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlF5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e16dc8c9bdb18dfbd333548089ce192f42e44cf/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
Feedback for changes:
1. Oppo type --> Utility Type
2. Utility Type dropdown list will be the ones tracked in the assessment
3. Energy savings unit would be the unit selected for the utility type (same unit selected in assessment)
4. Add a calculate button to calculate cost savings
<img width="1277" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHMxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0148759beb0a26d3958f127e0634bd63bb6aae74/image.png" alt="image.png" />
