### ISSUE TITLE
Move Maintenance Expense to KPI level

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#264]
currently it is a kpm under operations. It should be a large KPI level with different KPMs

**Comment by rmroot** [comment]
Move "Expense Cost" KPM's -> new "Maintenance Expenses" KPI

Add new KPMs to "Expense Cost":

**Comment by koay9f** [comment]
things to put in Expense Cost
service parts
treatment chemicals
raw materials
intermediate goods
 
things to put in maintenance cost
what was in expense costs
labor costs
3rd part labor

**Comment by rmroot** [comment]
I've noticed that if you have a KPI selected, there is no way to add in KPMs that have been deleted. or in this case a new KPM is added to our database. I added a modal similar to the NEBs that allows you to select KPMs that have been delete or newly added.

Additionally, it should be noted that KPMs in existing data (the demo for example) won't be moved automatically at this time.
