### ISSUE TITLE
Add Static Content

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#285]
Feedback Links:
Add a link for end users/testers to send feedback via email. Use kristina's email for now until we have a more established help desk email and larger user base

Additional Content: 
- About
- Help Page
- Acknowledgements

**Comment by rmroot** [comment]
A few updates:
content is in place some details need filling out. 
Hayden has opened a ticket for getting justifi-help@ornl.gov for feedback.
We want to add the advisory board members to the acknowledgments page. @RLiNREL is getting a list together

**Comment by RLiNREL** [comment]
most of the contents are updated in PR #312
Additional future changes:
- Update the support email
- Update content when more example data are added
