### ISSUE TITLE
Add Data Privacy Disclaimer

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#287]
add the general details about data privacy for the web version that we have in VERIFI and MEASUR. Should be a popup toast

**Comment by rmroot** [comment]
Add ability to disable disclaimer.

**Comment by koay9f** [comment]
the toast is good.  I think Gina also said in MEASUR & VERIFI that it needs to always be accessible. 
So maybe also add to about page? if not make a dedicated page

**Comment by RLiNREL** [comment]
Received some revised text from the comms, will commit it in.
