### ISSUE TITLE
KPI savings should be based on "baseline" not on costs

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#305]
If the KPI is cost per unit, KPI reduction should be based on actual amounts (either "Impact on KPI"/"Baseline Amount" for cost per unit).
This is only really important if the  user entered cost per unit = 0, so maybe that is the trigger?

Example: CO2 emissions:
<img width="1241" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VTQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bfdfb80b9680b24e78e530f63877a9083c4977b/image.png" alt="image.png" />

**Comment by koay9f** [comment]
Maybe the better solution would be to include baseline amount, units, annual change, and modified amount, and then do % change based on those...
or a separate table for KPM amounts....

**Comment by rmroot** [comment]
Updated table to calculate % change based off of baseline and modified amount of units if there are no cost values. Creating new issue for an additional table that gives details before/after amounts of impacts on individual KPMs
