### ISSUE TITLE
Branding and style foundation draft for NEB Tool

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#33]
Come up with initial branding and look and feel to implement the following pages in a more polished style:

- [ ] Splash page
- [ ] Company settings
- [ ] Facility settings page
- [ ] Project Dashboard page

UI elements include:
- [ ] Header
- [ ] Text headings
- [ ] Text fields and labels
- [ ] Sections in forms
- [ ] Navigation buttons
- [ ] Gray box to indicate "work in progress"
- [ ] ???

Must use NREL App template if hosted on NREL.gov

**Comment by rmroot** [comment]
Stale issue closing
