### ISSUE TITLE
Implement branding to splash page in Figma.

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#34]
- Lead branding conversation
- BLUE WORLD!!
- Implement color scheme and glyphs in splash page

Related to issue #33

**Comment by ghost** [comment]
I have taken a pass at this in the Figma board: https://www.figma.com/design/Czu5NsC2YK3yq12LVEDyPB/NEB-tool?node-id=0-1&t=9mj44h883mQrQrDL-0

<img width="905" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG8wQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--543dc82715914951fd0bda79356d43bb47d3f418/Screenshot%202024-06-04%20at%207.37.40%20AM.png" alt="Screenshot 2024-06-04 at 7.37.40 AM.png" />
