### ISSUE TITLE
Implement two NEBs on add nebs page for a given assessment

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#35]
- Select or create two NEBs that can relate to a demo assessment.
- Implement NEBs in the internal relational data structure, or a config file which is loaded into the data structure.
- NEBs are visible on NEB page as, eg, entries in a table.

- Initial nebs are located in Figma.

NEB Page: neb-tool/assessment/id/nebs
NEBs defined in Excel spreadsheet.

**Comment by jordanperr** [comment]
Not sure the spirit of this issue is solved. While we do now have the ability to add NEBs to projects, they are all custom NEBs with a "Connected KPI." Instead, the purpose of this issue is to upgrade these NEBs to have pre-defined types (such as a name, connected KPIs, and related energy systems and production processes) and also plan how to handle changes to these types moving forward. For example, the tool could read the NEBs definitions from a CSV or Excel file which is bundled with the tool.

**Comment by rmroot** [comment]
I think this issue is being tackled with #88

**Comment by ghost** [comment]
As of v0.0.1-alpha-f851d6b I believe the spirit of this issue is completed. User can add NEBs to assessments that relate to KPIs.
