### ISSUE TITLE
Import / Export system to NEB Tool Native JSON file(s)

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#39]
Implement initial import/export infrastructure for the internal data model.

User can:
- [x] Import / Export all the data in the tool to a file for safekeeping.
- [x] Import / Export the data for a single "Bulk Project", which contains 1 company, 1 facility, multiple assessments, and a report (may need further requirements)
- [ ] Gracefully handle conflicts in imported or exported data, or figure out how to avoid conflicts by restricting what can be saved.
- [x] Gracefully handle version changes between save file and app.
- [ ] Autosave to a file.

Please create new issues in the Inbox for any features listed in this description that will not be implemented.

**Comment by rmroot** [comment]
It's going to be best to borrow a lot of the structure of this from VERIFI. (https://github.com/ORNL-AMO/VERIFI/blob/develop/src/app/shared/helper-services/backup-data.service.ts)

What we want to do is click a "Backup Data" button and have all the data in the db backed up to a file that can be sent to someone to import. To accomplish this you create a json object that holds all the db entries and then download the file as a .json.

That piece is fairly straight forward. The trick is on the import. We will need to update all the "guid" values for the db entries. If we do not change the guid values then importing a file twice will mess up the system. The userId for all the entries will have to also match the importing users guid. 

I'll talk through all of this with Roy. 

Additionally on the backupdate file we will want to put a unique string like "justifi" that is checked to make sure the imported file is from the correct source and not a random .json file.

This issues will cover the first and third checkboxes that are outlined above, the remaining 2 checkbox will need new issues for a more robust import/export system down the line. At this time our main focus is getting a system in place where a tester can download and send a copy of the current state of their application to some other tester/developer for debugging.

**Comment by ghost** [comment]
I think we should add a "version" key to the exported file, which contains the version key of NEB Tool that generated the file. This way, we could implement migrations in the future.

**Comment by RLiNREL** [comment]
A version attribute is added to the backup file, and it is extracted from the app environment variables. The version check compares major, minor, patch, and pre-release, for example, v0.0.1-alpha, and ignores the build metadata added by Azure, v0.0.1-alpha-**5e4595a**
