### ISSUE TITLE
Testing framework / github actions as CI pipeline.

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#6]
- Decide between Travis CI vs Github actions runners
- Integrate with Angular testing framework
- Define testing requirements in contributing doc

**Comment by rmroot** [comment]
I have setup github actions to run our angular tests. and am creating a new issue to "Define testing requirements in contributing doc" #15

**Comment by rmroot** [comment]
Need to add for it to build on push for develop

**Comment by jordanperr** [comment]
I think we can call this closed for now. I will add an issue to the backlog for the documentation around testing requirements.
