### ISSUE TITLE
Child objects inherit metadata values from their parents.

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#61]
All metadata fields from parent objects should auto-fill into child objects in the project hierarchy. For example:

- The address of the Company should auto-fill in the Facility when a new one is created.
- If the user attempts to change a piece of metadata that is being inherited from a parent object, there should be a warning, and that reference is lost.
- (Maybe?) If a user updates the metadata in a parent object (Company), it should automatically propagate to children objects unless this behavior has been manually overridden.

**Comment by rmroot** [comment]
Inheritance is working with the unit changes from roy. This issue is stale. Closing
