### ISSUE TITLE
Implement first pass at "Pre-visit" "During-Visit" and "Post-Visit" workflows

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#64]
We have been working our way towards a three step workflow for users that includes a "Pre-visit", "During-Visit" and "Post-Visit". Currently our wizard just does the entire workflow in one go. Break up the wizard so it is more flexible given the context of use.

**Comment by rmroot** [comment]
Currently have Pre-visit and "Data Collection" (Formerly "On-Site") implemented. "Data Collection" (formerly "Post Visit) is a WIP. Placeholder content is there but not accessible at this time.

**Comment by jordanperr** [comment]
Reviewing v0.0.1-alpha-06d0278,

- Data members are saved as you go through the wizard. Final "Finish Pre-Visit" button is working now.
- There is now a modal to choose an existing company or create a new one.
- Will create new issues for "in progress" wizard and general wizard navigation.
