### ISSUE TITLE
Add Pre-Assessment Page to Pre-Visit

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#70]
there is a pre-assessment step, when you are setting up your assessment prior to running the assessment. Need to provide the general data at this step and then add the results in the onsite or post visit steps.

**Comment by jordanperr** [comment]
I'm not sure I follow the need for a separate "Pre-Assessment" page. Why not just define the assessments in the 2nd wizard when entering the results? If they don't have the results yet, they could simply leave those fields blank and then re-visit later.

**Comment by koay9f** [comment]
Biggest reason would be that we would want some things ready to go before we get to the actual visit.  I think this would be the last stage of the wizard and part of the "Turbo Tax" approach, kind of a "Let's get ready for the visit" page where you set it up, but when you get to the wizard in part 2 it's already started for you.

Also - this would be part of setting up things like the process/energy equipment and the fishbone diagram etc.

**Comment by ghost** [comment]
The pre-assessment page is integrated as of v0.0.1-alpha-996d421 and allows the user to add pre-assessments, which have an immutable date field, and contain a name, energy equipment, annual energy use, annual cost.

- It will be unclear to the user if "annual cost" should include or exclude the energy cost.
- Why is the date field immutable? What is the purpose of having a date field?
- Still not convinced we need a separate "pre assessment" data member. It seems to me that the concept of pre-assessments could be replaced entirely by a page to add "energy equipment".

I am going to create a new issue to review and update this page.

**Comment by ghost** [comment]
Closing this issue in favor of #120
