### ISSUE TITLE
Update Dashboards With New Data

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#75]
There's been a bunch of new data added to the various data pieces in setup and the dashboards have fallen behind. Take a pass through the dashboards to make sure everything still functions so that a potential early user can't get lost or break anything. 

- This will tie into the process of going from a pre-assessment to on-site assessment execution. 
- Currently the "Setup wizard" buttons in the dashboards do not function properly after all the changes

**Comment by jordanperr** [comment]
I am unsure exactly what to review here. We have all but abandoned the "My Portfolio" page to focus on the wizards. I do think it is still to have this page to quickly get to any data object in the model. But it needs a major refresh, as you say. I took a look at the "My Portfolio" page in v0.0.1-alpha-06d0278...

- Why is "Setup Wizard" used to add new assessments, whereas Facilities and Companies have their own "+ Add New" button and page.
- Shouldn't have two separate config UIs for the My Projects page and the Wizard. One of them should link to the other.
- The "Tabs" navigation is still confusing to me. I think "Explore NEBs", "Help", and "Settings" should be in the hamburger or top menu and we can do away with the tabs for now.

I think we should keep this page on ice for now (possibly even remove the link from the menu for MVP) and re-visit later if we feel we need to.

**Comment by jordanperr** [comment]
Added #97 to hide or update this page for MVP. Let's discuss these two issues.

**Comment by rmroot** [comment]
Stale Issue. Use #214 Closing
