### ISSUE TITLE
"Production Process" is the "End Use" of the energy, not the energy equipment.

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#83]
In the current version v0.0.1-alpha-c45ecba, the "Process Equipment" page seems to actually contain "energy equipment" such as boilers, fan, and compressed air. The intent of "Production Process" data member is to capture the end-use of the energy produced by the energy equipment, such as "Used in a paint booth" or "Used to clean the factory floor."

Actions:

- Change "Process Equipment" to be "Production Process" and switch the types of processes from energy equipment to end-uses (can use custom fields for now).
- Make new issue to evaluate the inclusion of "Energy Equipment" in an assessment. Or if we can simply create a new assessment for each piece of energy equipment.

**Comment by rmroot** [comment]
Not going to get to this at the moment. Going to work towards finishing a report and then loop back to equipment related content. This will drive NEB suggestion engine and be tied to assessments

**Comment by rmroot** [comment]
Updated process equipment to be db entry and added energy equipment. Process equipment doesn't do anything at the moment but have a name and notes field. issue #160 ties this equipment to the rest of the assessment

**Comment by ghost** [comment]
This has been implemented as of v0.0.1-alpha-3483233, with a new page in the wizard called "Process Equipment - End Uses" that allows the user to add custom equipment with a free-form string name, and notes. Other issues have been created to finish the integration of these production processes with the rest of the tool, including:

#78 - Add built-in types of production processes, as opposed to free-form text.
#98 - Integrate the presence of certain production processes into the NEB recommendation engine.
#126 - Integrate the production processes into reports.
#160 - Connect production processes to other areas of the assessment GUI.
