### ISSUE TITLE
Add new KPIs at the point in time when selecting NEBs

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#86]
Currently, the user can associate NEBs with existing KPIs through a drop-down menu on the NEB card. However, the user may discover new KPIs at this time, and so they should be able to add a new KPI easily from this part of the UI.

Quick-add KPI and Contacts, not on the KPI page.

**Comment by rmroot** [comment]
this will tie with #136 and may want to be done for the first demo.

Essentially we are only adding NEBs that have a metric tied to a KPI that is being tracked. We are going to add all NEBs to the modal. From their we can update the forms to have KPMs that are in untracked KPIs in the "Untracked Metrics" portion of the form. When added we can add the KPI to the company.

**Comment by ghost** [comment]
In version v0.0.1-alpha-66703bc, I am able to toggle the "Display NEBs without tracked KPMs" on the add NEBs modal. Adding such a neb to the assessment or energy opportunity results in a teal/blue box in the energy opportunity "Untracked Performance Metrics." Clicking on this box opens up a modal with a table showing Metric, KPI, and Category for each untracked KPI. Clicking the "+" button to the left of any KPI brings you to a confirmation modal asking "Would you like to add this performance metric:" and clicking "+ Add Metric" adds the metric to the project.

While this solves the spirit of the issue, I find the UI somewhat cumbersome to navigate. Especially the sequence of two modals that must be followed to add each untracked KPI. However, such a re-design will be covered by [Zenhub issue 5.](https://app.zenhub.com/workspaces/justifi---neb---ornl---nrel-61080603e73e7b0011bbdd7d/issues/zh/5)
