### ISSUE TITLE
Evaluate adding "Energy Equipment" data member to Energy Assessments

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#87]
Currently, we have one energy system per assessment in the data mode (E.g., Boiler Assessment). However, it may be the case that an energy manager inspects multiple boilers per assessment. We need to validate whether or not assessments in NEB Tool should have the granularity to go down to the individual pieces of energy equipment being assessed. If so, add a new data member to Energy Assessments called an "Energy Equipment."

**Comment by rmroot** [comment]
Added db entry for energy equipment. This equipment can be tied directly to an assessment with the dropdown in the assessment form. Creating issue to incorporate kristina's feedback on the form in which the fields shown are driven by the Energy Equipment System selection. (#163)

**Comment by ghost** [comment]
This feature has been implemented as of v0.0.1-alpha-3483233.
