### ISSUE TITLE
Navigation To Initial Report

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#94]
Setup navigation for the "Data Evaluation" portion of the wizard that gets us to a "Report". 

This issue can be used for the initial navigation and create a secondary issue for some initial content.

- Report should show up in the third wizard section.
- At first, we could auto-populate this wizard with a single page for each energy project-level report.
- In the future, we would allow the user to create and delete reports for different levels of the data model.

**Comment by ghost** [comment]
Works for me as of v0.0.1-alpha-c933213. Assessment-level reports for each assessment are auto-populated as pages in the third wizard.

Adding features for different levels of report rollups is defined in #128.
