### ISSUE TITLE
Hide or update "My Projects" page for MVP

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#97]
Out of #75 

The "My Projects" page is pretty rough right now, and I'm not sure it is needed for the MVP and may just cause more confusion. Here are the minimal changes I think would be needed to keep this page in an MVP:

**Option 1: Update "My Projects"**:
- [ ] Remove the tabs and move "Help" "Explore Nebs" and "Settings" to the hamburger menu.
- [ ] Remove the company->facility heirarchy from the hamburger menu.
- [ ] Remove import/export buttons in Facility and Company views.
- [ ] Why is the green button in "Assessments" table "Setup Wizard" whereas it is "+ Add New" in Facility and Company tables?
- [ ] Just general cleanup / simplification of the My Portfolio tables.

However, I would strongly recommend just disabling this page entirely. In that case, the tasks are:

**Option 2: Hide "My Projects"**:
- [ ] Remove the tabs and move "Help" "Explore Nebs" and "Settings" to the hamburger menu.
- [ ] Remove "My Project" button from the hamburger menu"
- [ ] Remove the company->facility heirarchy from the hamburger menu.

**Comment by rmroot** [comment]
Stale Issue. Closing
